# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-20 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phoneprice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('maxprice', models.IntegerField()),
                ('opprice', models.IntegerField()),
                ('pprice', models.IntegerField()),
            ],
        ),
    ]
